### ISSUE TITLE
1.14 update checklist

### ISSUE THREAD

**Issue by elidupree** [elidupree/EoHS#169]
Critical:
- [ ] make change terrain usable through the new UI
- [ ] fix Mentor in multiple ways
- [ ] show can't cast messages
- [ ] fix (remove?) the unit_weapons texts during targeting (they currently don't update in time, like the gold theme item before I fixed it)

Minor:
- [ ] Arrange the spells nicely 
- [ ] fix displaying the movement range of the selected unit during spellcasting UI
- [ ] fix the visual glitches for displayed depletion of both gold/mana and action points (situations where it redisplays at your full amount before deducting them again)
- [ ] Make a way to use Scribe in the new UI
